language: node_js
node_js:
  - "node"
services:
  - postgresql
  
group: deprecated-2017Q3
 
before_script:
  - npm install -g sequelize-cli
  - sudo -u postgres createuser mcdavid
  - createdb contacts-test

script:
  - npm run test